language: node_js
node_js:
  - "8"
script:
  - npm run build
deploy:
  provider: pages
  edge:
    branch: pages-ivar-set
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: build
  on:
    tags: true
