language: node_js
node_js:
  - "8"
addons:
  apt:
    packages:
      - oracle-java8-set-default 
install:
  - bash -c "curl -s "https://get.sdkman.io" | bash"
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install kotlin
  - npm install
before_script:
  - java -version
script:
  - npm run build --verbose
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    tags: true