language: node_js
node_js:
  - "8"
addons:
  apt:
    packages:
      - oracle-java8-set-default 
before_script:
  - env
script:
  - npm run build --verbose
after_script:
  - cat /home/travis/.npm/_logs/*
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    tags: true