language: node_js
node_js:
  - "8"
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - "node_modules"
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    tags: true