language: node_js
node_js:
  - "8"
addons:
  apt:
    packages:
      - oracle-java8-set-default 
before_script:
  - unset _JAVA_OPTIONS
script:
  - npm run build
deploy:
  provider: pages
  edge:
    branch: pages-ivar-set
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: build
  on:
    tags: true
