name: Build workspaces
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build --workspaces
    - run: npm run test --workspaces --if-present

    - name: Upload vue-version artifact
      uses: actions/upload-artifact@v1
      with:
        name: github-pages
        path: ./packages/piano-vue/dist