name: Build workspaces
on:
  push:
    branches-ignore:
      - "main"
  workflow_call:

jobs:
  workspaces:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build --workspaces
    - run: npm run test:coverage --workspaces --if-present

    - name: Upload vue-version artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./packages/piano-vue/dist